name: Deploy
on: push
  
jobs:
  first_jobs:
    name: tutorial codigoFacilito actions
    runs-on: ubuntu-latest

    steps:
      - name: working dir
        id: steps_1
        run: echo "mi_variable_hola mundo" >> $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo "${{ steps_1.outputs.mi_variable_hola }}"


      - name: action
        uses: action/checkout@v4
    

      - name: working dir after action
        run: ls -al  