name: Deploy
on: push
  
jobs:
  first_jobs:
    name: tutorial codigoFacilito actions
    runs-on: ubuntu-latest

    steps:
      - name: working dir
        run: ls -al

      - name: action
        uses: action/checkout@v4

      - name: working dir after action
        run: ls -al  